### ISSUE TITLE
formatter support

### ISSUE THREAD

**Issue by pavles6** [jkasky/zed-cue#2]
Any plans on adding support for formatting via `cue fmt`?

Currently this in `settings.json` does not seem to work:
```json
 "CUE": {
      "format_on_save": {
        "external": {
          "command": "cue",
          "arguments": ["fmt", "{buffer_path}"]
        }
      }
    }
```

**Comment by jkasky** [comment]
@pavles6 - I played around with my settings a bit and was able to get something working. I'm running v0.149.3. Let me know if this works for you. 

```json
"languages": {
    "CUE": {
      "format_on_save": "on",
      "formatter": {
        "external": {
          "command": "cue",
          "arguments": ["fmt", "-"]
        }
      }
    }
  },
```

This extension currently only supports syntax highlighting and outline of CUE files. Formatting could be supported by a language server but last time I checked there wasn't a complete LSP implementation for CUE yet.

**Comment by jkasky** [comment]
Looks like there is some progress being made on an official cue LSP https://github.com/cue-lang/cue/blob/master/cmd/cuepls/main.go, once that gets closer to being ready to use it can be added to this extension for richer language support, in addition to formatting through the language server.

**Comment by pavles6** [comment]
Cool, the snippet above worked. IDK how I missed that, I've tried dozen of different configration opts. Thank you so much for assistance with this, and the amazing extension! Can't wait to for the official LSP to get integrated

**Comment by jkasky** [comment]
Version v0.0.3 includes 33a94fffc0b3f9349160518b434feff1145c35b5, which adds support for `cuepls` language server. As of now `cuepls` only supports formatting so the external command in settings to get 'format on save' working is no longer necessary.

**Comment by pasteley** [comment]
@jkasky Can we fix formatting now, after migration to `cue` binary? https://github.com/jkasky/zed-cue/pull/3

**Comment by pavles6** [comment]
@pasteley formatting works for me even after cue `0.11.0` LSP migration. Just make sure to update your cue binary to latest version in your local env.

**Comment by jkasky** [comment]
Formatting is now handled by cue lsp. The extension handles downloading the latest cue binary and running the language server in the same way that other language extensions work.

**Comment by pasteley** [comment]
> @pasteley formatting works for me even after cue `0.11.0` LSP migration. Just make sure to update your cue binary to latest version in your local env.

Oh, I see now, thank you.

> Formatting is now handled by cue lsp.

don't you mind to add it to README alongside with the requirements for the cue version?

**Comment by pavles6** [comment]
@pasteley I agree that that would be helpful for others. I'll create a PR to add this info
